# Theme: Everforest Dark Hard
background            #272e33
foreground            #d3c6aa
# Black
color0  #41484d
color8  #41484d

# Red
color1  #e67e80
color9  #e67e80

# Green
color2  #a7c080
color10 #a7c080

# Yellow
color3  #dbbc7f
color11 #dbbc7f

# Blue
color4  #7fbbb3
color12 #7fbbb3

# Magenta
color5  #d699b6
color13 #d699b6

# Cyan
color6  #83c092
color14 #83c092

# White
color7  #d3c6aa
color15 #d3c6aa

# Cursor & Selection
cursor                #d3c6aa
selection_background  #475258

# Fonts (Assumes you have a Nerd Font installed)
font_family      JetBrainsMono Nerd Font
font_size        15.0

# macOS Specific Tweaks
window_padding_width 10
background_opacity 0.9
background_blur 20

# Performance
repaint_delay 8
input_delay 1
sync_to_monitor yes

# Keymaps (Option as Alt for Neovim)
macos_option_as_alt left
